"""Conservative cleanup for Markdown exported by Docling.

The cleaner deliberately does not infer product facts. It only removes parser
artifacts that can be identified from their structure, while keeping tables,
headings, measurements, links, and numbered instructions intact.
"""

from __future__ import annotations

import html
import re


# Artifacts that are unambiguously generated by the PDF/Markdown parser.
_IMAGE_COMMENT = re.compile(r"^\s*<!--\s*(?:image|figure)\s*-->\s*$", re.I)
_HTML_COMMENT = re.compile(r"<!--.*?-->", re.S)
_CONTROL_CHARACTERS = re.compile(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]")
_REPLACEMENT_CHARACTER = re.compile(r"(?:�|ï¿½)")
_DECORATIVE_SUFFIX = re.compile(r"(?:\\_|_){3,}\s*$")
_HEADING_FOOTNOTE = re.compile(r"^(#{2,6}\s+.*?)(?:\s+[0-9]{1,3})\s*$")

# Generic document-structure patterns. They are intentionally language
# neutral apart from common Turkish/English TOC labels.
_TOC_HEADING = re.compile(
    r"^\s*(?:#+\s*)?(?:İÇERİK|İÇİNDEKİLER|TABLE OF CONTENTS|CONTENTS)\s*$",
    re.I,
)
_TOC_ROW = re.compile(
    r"^\s*\|.*(?:\.{3,}|…{2,}).*\|?\s*[0-9]{1,3}\s*\|?\s*$"
)
_TOC_LABEL = re.compile(r"(?:İÇERİK|İÇİNDEKİLER|TABLE OF CONTENTS|CONTENTS)", re.I)

# A long technical heading such as `## Width: 71 mm Height: 120 mm` is a
# parser error. This expression activates only when at least two label:value
# pairs are present.
_FIELD_LABEL = (
    r"[A-ZÇĞİÖŞÜ][\wÇĞİÖŞÜçğıöşü()/'-]*"
    r"(?:\s+[A-ZÇĞİÖŞÜ][\wÇĞİÖŞÜçğıöşü()/'-]*){0,3}"
)
_STRUCTURED_FIELD = re.compile(
    rf"({_FIELD_LABEL})\s*:\s*(.*?)(?=\s+{_FIELD_LABEL}\s*:|$)"
)


def _normalize_text(text: str) -> str:
    """Normalize safe character-level parser artifacts."""

    text = html.unescape(text.replace("\u00a0", " "))
    text = _CONTROL_CHARACTERS.sub(" ", text)
    text = _REPLACEMENT_CHARACTER.sub(" ", text)

    # Common remnants of Windows-code-page output. Only change them when
    # surrounded by word characters so genuine symbols in URLs/measurements
    # are not modified.
    for broken, corrected in {"€": "ğ", "›": "ı"}.items():
        text = re.sub(
            rf"(?<=\w){re.escape(broken)}(?=\w|\s|[.,;:!?)]|$)",
            corrected,
            text,
        )

    # Remove image/figure comments, but preserve ordinary HTML comments that
    # may carry useful text.
    text = _HTML_COMMENT.sub(
        lambda match: "" if _IMAGE_COMMENT.match(match.group(0)) else match.group(0),
        text,
    )
    return text


def _remove_table_of_contents(lines: list[str]) -> list[str]:
    """Remove explicit or structurally obvious table-of-contents blocks."""

    result: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]

        if _TOC_HEADING.match(line.strip()):
            index += 1
            while index < len(lines) and not re.match(r"^#{1,6}\s+", lines[index].strip()):
                index += 1
            continue

        if _TOC_ROW.match(line):
            end = index
            matches = 0
            while end < len(lines) and lines[end].strip().startswith("|"):
                matches += bool(_TOC_ROW.match(lines[end]))
                end += 1
            if matches >= 3:
                index = end
                continue

        if line.strip().startswith("|"):
            end = index
            table_lines: list[str] = []
            while end < len(lines) and lines[end].strip().startswith("|"):
                table_lines.append(lines[end])
                end += 1
            if _TOC_LABEL.search("\n".join(table_lines)):
                index = end
                continue

        result.append(line)
        index += 1
    return result


def _normalize_heading(line: str) -> str:
    """Remove only structural noise from a Markdown heading."""

    if not line.lstrip().startswith("#"):
        return line.rstrip()

    line = _DECORATIVE_SUFFIX.sub("", line.rstrip()).rstrip()
    footnote = _HEADING_FOOTNOTE.match(line)
    return footnote.group(1).rstrip() if footnote else line


def _split_structured_heading(line: str, recent_lines: list[str]) -> list[str]:
    """Turn a parser-created field heading into readable field lines.

    A normal short heading such as `## Battery` remains untouched.
    """

    match = re.match(r"^##\s+(.+)$", line)
    if not match:
        return [line]

    fields = list(_STRUCTURED_FIELD.finditer(match.group(1)))
    if len(fields) < 2:
        return [line]

    # Keep a stable generic section heading. Do not guess a category from the
    # field names, since the same rule must work for any product type.
    prefix = []
    if not any(item.strip() == "## Özellikler" for item in recent_lines[-3:]):
        prefix.append("## Özellikler")

    values = []
    for field in fields:
        value = re.sub(r"\s+,", ",", field.group(2).strip())
        values.append(f"- {field.group(1).strip()}: {value}")
    return prefix + values


def _normalize_spacing(lines: list[str]) -> list[str]:
    """Normalize blank lines without changing table cell content."""

    result: list[str] = []
    previous_blank = False
    for line in lines:
        line = line.rstrip()
        is_blank = not line.strip()
        if is_blank and previous_blank:
            continue
        result.append(line)
        previous_blank = is_blank
    return result


def _repair_evidence_backed_word_splits(text: str) -> str:
    """Repair only word splits proven by another occurrence in the document.

    If the intact word never occurs elsewhere, the cleaner leaves the source
    untouched instead of guessing what the OCR output meant.
    """

    words = {
        match.group(0).casefold()
        for match in re.finditer(r"[^\W\d_]+", text, flags=re.UNICODE)
    }
    split_word = re.compile(
        r"(?P<left>[^\W\d_]{1,3})[ \t]+(?P<right>[^\W\d_]{2,})"
    )

    def repair_line(line: str) -> str:
        def replace(match: re.Match[str]) -> str:
            combined = match.group("left") + match.group("right")
            return combined if combined.casefold() in words else match.group(0)

        return split_word.sub(replace, line)

    return "\n".join(repair_line(line) for line in text.splitlines())


def clean_docling_markdown(markdown: str) -> str:
    """Clean Docling Markdown while preserving source meaning and structure."""

    if not markdown or not markdown.strip():
        return ""

    normalized = _normalize_text(markdown)
    lines = _remove_table_of_contents(normalized.splitlines())

    cleaned: list[str] = []
    for line in lines:
        if _IMAGE_COMMENT.match(line):
            continue
        heading = _normalize_heading(line)
        cleaned.extend(_split_structured_heading(heading, cleaned))

    cleaned = _normalize_spacing(cleaned)
    result = "\n".join(cleaned).strip()
    return _repair_evidence_backed_word_splits(result).strip()
